import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'cream-surface': '#F5E6D3',
        'surface-dim': '#210e0b',
        'tertiary-fixed': '#ffdbd0',
        'on-surface-variant': '#dcc1ae',
        'surface-container-high': '#3b2420',
        'secondary-fixed-dim': '#9cd67a',
        'on-primary-fixed-variant': '#6d3a00',
        'surface-container-low': '#2b1613',
        'surface-variant': '#472f2b',
        'on-primary-fixed': '#2e1500',
        'secondary': '#9cd67a',
        'primary-fixed': '#ffdcc2',
        'wood-dark': '#2C1810',
        'on-primary': '#4c2700',
        'surface': '#210e0b',
        'inverse-on-surface': '#422a26',
        'surface-container-lowest': '#1b0906',
        'on-background': '#ffdad4',
        'surface-container-highest': '#472f2b',
        'status-warning': '#FFC107',
        'on-tertiary-fixed': '#3a0b00',
        'on-secondary-fixed-variant': '#205102',
        'outline': '#a48c7a',
        'on-error': '#690005',
        'error-container': '#93000a',
        'wood-medium': '#4E342E',
        'wood-border': '#5D4037',
        'inverse-primary': '#8f4e00',
        'secondary-container': '#225404',
        'sky-blue': '#87CEEB',
        'error': '#ffb4ab',
        'on-surface': '#ffdad4',
        'surface-bright': '#4c332f',
        'primary': '#ffb87b',
        'inverse-surface': '#ffdad4',
        'outline-variant': '#564334',
        'on-secondary-fixed': '#082100',
        'primary-fixed-dim': '#ffb77a',
        'surface-tint': '#ffb77a',
        'on-error-container': '#ffdad6',
        'background': '#210e0b',
        'tertiary-fixed-dim': '#ffb59e',
        'primary-container': '#ff8f00',
        'status-success': '#4CAF50',
        'tertiary-container': '#fe8c68',
        'on-primary-container': '#623400',
        'status-info': '#2196F3',
        'tertiary': '#ffb59f',
        'on-tertiary-fixed-variant': '#7e2b0f',
        'on-secondary-container': '#8fc86d',
        'gold-currency': '#FFD700',
        'on-tertiary-container': '#742408',
        'on-tertiary': '#5e1700',
        'sky-deep': '#4A7FB5',
        'surface-container': '#2f1a16',
        'on-secondary': '#133800',
        'status-danger': '#C62828',
        'secondary-fixed': '#b7f393',
        molemisi: {
          earth: '#C05C3C',
          brown: '#8B5E3C',
          sand: '#E8D5A3',
          grass: '#5A8F3C',
          sky: '#87CEEB',
          sunset: '#E8945A',
          night: '#2C1810',
          panel: '#3E2723',
          border: '#5D4037',
          text: '#F5E6D3',
          muted: '#BCAAA4',
          accent: '#FF8F00',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '0.75rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'pixel-1': '0.125rem',
        'pixel-2': '0.25rem',
        'space-2xl': '2rem',
        'space-lg': '1rem',
        'gutter-desktop': '1.5rem',
        'space-xl': '1.5rem',
      },
      fontFamily: {
        headline: ['var(--font-molemisi-pixel)', 'Space Grotesk', 'sans-serif'],
        body: ['var(--font-rubik)', 'Rubik', 'sans-serif'],
        mono: ['var(--font-space-mono)', 'Space Mono', 'monospace'],
        'headline-lg-mobile': ['var(--font-molemisi-pixel)', 'Space Grotesk', 'sans-serif'],
        'headline-lg': ['var(--font-molemisi-pixel)', 'Space Grotesk', 'sans-serif'],
        'headline-md': ['var(--font-molemisi-pixel)', 'Space Grotesk', 'sans-serif'],
        'headline-sm': ['var(--font-molemisi-pixel)', 'Space Grotesk', 'sans-serif'],
        'body-lg': ['var(--font-rubik)', 'Rubik', 'sans-serif'],
        'body-md': ['var(--font-rubik)', 'Rubik', 'sans-serif'],
        'body-sm': ['var(--font-rubik)', 'Rubik', 'sans-serif'],
        'label-lg': ['var(--font-space-mono)', 'Space Mono', 'monospace'],
        'label-md': ['var(--font-space-mono)', 'Space Mono', 'monospace'],
        'label-sm': ['var(--font-space-mono)', 'Space Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;
