export interface CropConfig {
  id: string;
  name: string;
  description: string;
  unlockLevel: number;
  growthStages: number;
  timePerStage: number; // minutes
  waterDecayRate: number; // per game hour
  waterPerAction: number;
  diseaseChancePerStage: number;
  pestChancePerStage: number;
  yield: { min: number; max: number };
  seedCost: number;
  basePrice: number;
  spriteSheet: string;
}

export const CROPS: Record<string, CropConfig> = {
  sorghum: {
    id: 'sorghum',
    name: 'Sorghum',
    description: 'A hardy grain crop, staple of Botswana agriculture.',
    unlockLevel: 1,
    growthStages: 4,
    timePerStage: 3,
    waterDecayRate: 0.1,
    waterPerAction: 1,
    diseaseChancePerStage: 0.05,
    pestChancePerStage: 0.03,
    yield: { min: 3, max: 5 },
    seedCost: 5,
    basePrice: 15,
    spriteSheet: 'crop_sorghum_stages.png',
  },
  maize: {
    id: 'maize',
    name: 'Maize',
    description: 'Versatile grain used for food and feed.',
    unlockLevel: 1,
    growthStages: 5,
    timePerStage: 4,
    waterDecayRate: 0.15,
    waterPerAction: 2,
    diseaseChancePerStage: 0.08,
    pestChancePerStage: 0.06,
    yield: { min: 4, max: 6 },
    seedCost: 8,
    basePrice: 20,
    spriteSheet: 'crop_maize_stages.png',
  },
  millet: {
    id: 'millet',
    name: 'Millet',
    description: 'Fast-growing grain, drought resistant.',
    unlockLevel: 2,
    growthStages: 4,
    timePerStage: 2.5,
    waterDecayRate: 0.08,
    waterPerAction: 1,
    diseaseChancePerStage: 0.04,
    pestChancePerStage: 0.02,
    yield: { min: 2, max: 4 },
    seedCost: 4,
    basePrice: 12,
    spriteSheet: 'crop_millet_stages.png',
  },
  cowpeas: {
    id: 'cowpeas',
    name: 'Cowpeas',
    description: 'Nutritious legume, fixes nitrogen in soil.',
    unlockLevel: 3,
    growthStages: 4,
    timePerStage: 3.5,
    waterDecayRate: 0.1,
    waterPerAction: 1,
    diseaseChancePerStage: 0.05,
    pestChancePerStage: 0.03,
    yield: { min: 3, max: 5 },
    seedCost: 6,
    basePrice: 18,
    spriteSheet: 'crop_cowpeas_stages.png',
  },
  groundnuts: {
    id: 'groundnuts',
    name: 'Groundnuts',
    description: 'Valuable oilseed crop.',
    unlockLevel: 4,
    growthStages: 5,
    timePerStage: 5,
    waterDecayRate: 0.12,
    waterPerAction: 2,
    diseaseChancePerStage: 0.07,
    pestChancePerStage: 0.08,
    yield: { min: 4, max: 7 },
    seedCost: 10,
    basePrice: 25,
    spriteSheet: 'crop_groundnuts_stages.png',
  },
  sesame: {
    id: 'sesame',
    name: 'Sesame',
    description: 'Premium oilseed, high value.',
    unlockLevel: 5,
    growthStages: 4,
    timePerStage: 4,
    waterDecayRate: 0.09,
    waterPerAction: 1,
    diseaseChancePerStage: 0.04,
    pestChancePerStage: 0.03,
    yield: { min: 2, max: 3 },
    seedCost: 15,
    basePrice: 35,
    spriteSheet: 'crop_sesame_stages.png',
  },
  watermelon: {
    id: 'watermelon',
    name: 'Watermelon',
    description: 'Refreshing fruit, high water requirement.',
    unlockLevel: 6,
    growthStages: 6,
    timePerStage: 5,
    waterDecayRate: 0.18,
    waterPerAction: 3,
    diseaseChancePerStage: 0.1,
    pestChancePerStage: 0.06,
    yield: { min: 2, max: 4 },
    seedCost: 20,
    basePrice: 40,
    spriteSheet: 'crop_watermelon_stages.png',
  },
  tomatoes: {
    id: 'tomatoes',
    name: 'Tomatoes',
    description: 'Popular vegetable, versatile.',
    unlockLevel: 7,
    growthStages: 5,
    timePerStage: 3,
    waterDecayRate: 0.14,
    waterPerAction: 2,
    diseaseChancePerStage: 0.09,
    pestChancePerStage: 0.06,
    yield: { min: 5, max: 8 },
    seedCost: 12,
    basePrice: 22,
    spriteSheet: 'crop_tomatoes_stages.png',
  },
  pepper: {
    id: 'pepper',
    name: 'Pepper',
    description: 'Spicy crop, high market value.',
    unlockLevel: 8,
    growthStages: 4,
    timePerStage: 4,
    waterDecayRate: 0.1,
    waterPerAction: 1,
    diseaseChancePerStage: 0.06,
    pestChancePerStage: 0.04,
    yield: { min: 3, max: 5 },
    seedCost: 25,
    basePrice: 45,
    spriteSheet: 'crop_pepper_stages.png',
  },
  herbs: {
    id: 'herbs',
    name: 'Herbs',
    description: 'Medicinal and culinary herbs.',
    unlockLevel: 9,
    growthStages: 3,
    timePerStage: 6,
    waterDecayRate: 0.08,
    waterPerAction: 1,
    diseaseChancePerStage: 0.03,
    pestChancePerStage: 0.02,
    yield: { min: 1, max: 3 },
    seedCost: 40,
    basePrice: 80,
    spriteSheet: 'crop_herbs_stages.png',
  },
  saffron: {
    id: 'saffron',
    name: 'Saffron',
    description: 'Precious spice, extremely valuable.',
    unlockLevel: 10,
    growthStages: 5,
    timePerStage: 8,
    waterDecayRate: 0.07,
    waterPerAction: 1,
    diseaseChancePerStage: 0.04,
    pestChancePerStage: 0.03,
    yield: { min: 1, max: 2 },
    seedCost: 80,
    basePrice: 200,
    spriteSheet: 'crop_saffron_stages.png',
  },
};

export function getCropConfig(cropType: string): CropConfig | undefined {
  return CROPS[cropType];
}

export function getUnlockedCrops(level: number): CropConfig[] {
  return Object.values(CROPS).filter((crop) => crop.unlockLevel <= level);
}
