/**
 * Molemisi Pixel — game font loader.
 *
 * Two grids, both generated by scripts/generate-font.mjs and synced by
 * scripts/build-font.mjs:
 *   'Molemisi Pixel'       — 16px grid, canonical display font (panels 14px+)
 *   'Molemisi Pixel Small' — 8px dense grid for small HUD/panel text (12-13px)
 *
 * Long-form dialogue intentionally keeps Rubik for readability.
 */

export const FONT_DISPLAY = "'Molemisi Pixel', monospace";
export const FONT_SMALL = "'Molemisi Pixel Small', 'Molemisi Pixel', monospace";
export const FONT_BODY = 'Rubik, sans-serif';
export const FONT_MONO = "'Space Mono', 'Molemisi Pixel', monospace";

const FACES: Array<{ family: string; url: string }> = [
  { family: 'Molemisi Pixel', url: '/fonts/MolemisiPixel-Bold.ttf' },
  { family: 'Molemisi Pixel Small', url: '/fonts/MolemisiPixel-Small.ttf' },
];

let fontPromise: Promise<void> | null = null;

/** Kick off font registration exactly once. */
export function ensureGameFont(): Promise<void> {
  if (fontPromise) return fontPromise;
  fontPromise = (async () => {
    if (typeof document === 'undefined') return;
    if (!('fonts' in document)) return; // very old browser — let fallbacks handle it

    for (const { family, url } of FACES) {
      const face = new FontFace(family, `url(${url})`, {
        weight: '700',
        style: 'normal',
        display: 'swap',
      });
      document.fonts.add(face);
      try {
        await face.load();
        console.log(`[font] ${family} loaded`);
      } catch (e) {
        console.warn(`[font] ${family} failed to load, using fallbacks:`, e);
      }
    }
    await document.fonts.ready;
  })();
  return fontPromise;
}
