// AUTO-GENERATED by scripts/sync-assets.mjs — do not edit.
// Derived from assets/manifest.json (written by scripts/generate-pixellab-assets.mjs).

export interface GeneratedAsset {
  id: string;
  file: string;
  width: number;
  height: number;
  kind: string;
  group: string;
}

export const ASSET_MANIFEST: GeneratedAsset[] = [
  {
    "id": "acacia_tree",
    "file": "tiles/decorations/acacia_tree.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "animal_track",
    "file": "sprites/scene-props/animal_track.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "animals_collect",
    "file": "ui/icons/animals_collect.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "animals_feed",
    "file": "ui/icons/animals_feed.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "animals_heal",
    "file": "ui/icons/animals_heal.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "animals_pet",
    "file": "ui/icons/animals_pet.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "animals_shelter",
    "file": "ui/icons/animals_shelter.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "baobab_tree",
    "file": "tiles/decorations/baobab_tree.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "barn_lvl1",
    "file": "sprites/buildings/barn/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "building_barn",
    "file": "ui/items/building_barn.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_borehole",
    "file": "ui/items/building_borehole.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_coop",
    "file": "ui/items/building_coop.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_goat_pen",
    "file": "ui/items/building_goat_pen.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_greenhouse",
    "file": "ui/items/building_greenhouse.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_mill",
    "file": "ui/items/building_mill.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_paddock",
    "file": "ui/items/building_paddock.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_pig_pen",
    "file": "ui/items/building_pig_pen.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "building_well",
    "file": "ui/items/building_well.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "buildings_construct",
    "file": "ui/icons/buildings_construct.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "buildings_demolish",
    "file": "ui/icons/buildings_demolish.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "buildings_repair",
    "file": "ui/icons/buildings_repair.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "buildings_upgrade",
    "file": "ui/icons/buildings_upgrade.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "bush",
    "file": "tiles/decorations/bush.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "bush_camp",
    "file": "sprites/scene-props/bush_camp.png",
    "width": 48,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "bushveld_riverbank",
    "file": "tiles/sky/bushveld_riverbank.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "bushveld_savanna",
    "file": "tiles/sky/bushveld_savanna.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "bushveld_scout",
    "file": "sprites/npcs/bushveld_scout.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "npcs"
  },
  {
    "id": "button_danger",
    "file": "ui/buttons/button_danger.png",
    "width": 96,
    "height": 48,
    "kind": "pixen",
    "group": "ui-assets"
  },
  {
    "id": "button_primary",
    "file": "ui/buttons/button_primary.png",
    "width": 96,
    "height": 48,
    "kind": "pixen",
    "group": "ui-assets"
  },
  {
    "id": "button_secondary",
    "file": "ui/buttons/button_secondary.png",
    "width": 96,
    "height": 48,
    "kind": "pixen",
    "group": "ui-assets"
  },
  {
    "id": "cave_entrance",
    "file": "sprites/scene-props/cave_entrance.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "chicken_happy",
    "file": "sprites/animals/chicken/happy.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "chicken_idle",
    "file": "sprites/animals/chicken/idle.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "chicken_product",
    "file": "sprites/animals/chicken/product.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "cloud_storm",
    "file": "weather/cloud_storm.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "weather"
  },
  {
    "id": "cloud_white",
    "file": "weather/cloud_white.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "weather"
  },
  {
    "id": "coin",
    "file": "particles/coin.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "community_circle",
    "file": "sprites/scene-props/community_circle.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "coop_lvl1",
    "file": "sprites/buildings/coop/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "cow_happy",
    "file": "sprites/animals/cow/happy.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "cow_idle",
    "file": "sprites/animals/cow/idle.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "cow_product",
    "file": "sprites/animals/cow/product.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "cowpeas_product",
    "file": "sprites/crops/cowpeas/product_cowpeas.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "cowpeas_seed",
    "file": "sprites/crops/cowpeas/seed_cowpeas.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "cowpeas_stage_0",
    "file": "sprites/crops/cowpeas/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "cowpeas_stage_1",
    "file": "sprites/crops/cowpeas/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "cowpeas_stage_2",
    "file": "sprites/crops/cowpeas/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "cowpeas_stage_3",
    "file": "sprites/crops/cowpeas/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "currency_gem",
    "file": "ui/icons/currency_gem.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "currency_pula",
    "file": "ui/icons/currency_pula.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "currency_token",
    "file": "ui/icons/currency_token.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "dirt_chunk",
    "file": "particles/dirt_chunk.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "dust_puff",
    "file": "particles/dust_puff.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "elder_chair",
    "file": "sprites/scene-props/elder_chair.png",
    "width": 48,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "elder_neo",
    "file": "sprites/npcs/elder_neo.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "npcs"
  },
  {
    "id": "farm_day",
    "file": "tiles/sky/farm_day.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "farm_night",
    "file": "tiles/sky/farm_night.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "farm_sunset",
    "file": "tiles/sky/farm_sunset.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "farming_fertilize",
    "file": "ui/icons/farming_fertilize.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "farming_harvest",
    "file": "ui/icons/farming_harvest.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "farming_plant",
    "file": "ui/icons/farming_plant.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "farming_soil",
    "file": "ui/icons/farming_soil.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "farming_water",
    "file": "ui/icons/farming_water.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "farming_weed",
    "file": "ui/icons/farming_weed.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "fence",
    "file": "tiles/decorations/fence.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "fire_pit",
    "file": "sprites/scene-props/fire_pit.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "flower_patch",
    "file": "tiles/decorations/flower_patch.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "food_stall",
    "file": "sprites/scene-props/food_stall.png",
    "width": 48,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "goat_happy",
    "file": "sprites/animals/goat/happy.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "goat_idle",
    "file": "sprites/animals/goat/idle.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "goat_pen_lvl1",
    "file": "sprites/buildings/goat_pen/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "goat_product",
    "file": "sprites/animals/goat/product.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "goods_display",
    "file": "sprites/scene-props/goods_display.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "grass_base",
    "file": "tiles/ground/grass_base.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "ground"
  },
  {
    "id": "grass_dirt",
    "file": "tiles/ground/grass_dirt.json",
    "width": 16,
    "height": 16,
    "kind": "tileset",
    "group": "ground"
  },
  {
    "id": "grass_dry",
    "file": "tiles/ground/grass_dry.json",
    "width": 16,
    "height": 16,
    "kind": "tileset",
    "group": "ground"
  },
  {
    "id": "grass_path",
    "file": "tiles/ground/grass_path.json",
    "width": 16,
    "height": 16,
    "kind": "tileset",
    "group": "ground"
  },
  {
    "id": "grass_tuft",
    "file": "tiles/decorations/grass_tuft.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "grass_water",
    "file": "tiles/ground/grass_water.json",
    "width": 16,
    "height": 16,
    "kind": "tileset",
    "group": "ground"
  },
  {
    "id": "groundnuts_product",
    "file": "sprites/crops/groundnuts/product_groundnuts.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "groundnuts_seed",
    "file": "sprites/crops/groundnuts/seed_groundnuts.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "groundnuts_stage_0",
    "file": "sprites/crops/groundnuts/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "groundnuts_stage_1",
    "file": "sprites/crops/groundnuts/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "groundnuts_stage_2",
    "file": "sprites/crops/groundnuts/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "groundnuts_stage_3",
    "file": "sprites/crops/groundnuts/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "groundnuts_stage_4",
    "file": "sprites/crops/groundnuts/stage_4.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "heart",
    "file": "particles/heart.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "herb_garden",
    "file": "sprites/scene-props/herb_garden.png",
    "width": 64,
    "height": 32,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "herbs_product",
    "file": "sprites/crops/herbs/product_herbs.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "herbs_seed",
    "file": "sprites/crops/herbs/seed_herbs.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "herbs_stage_0",
    "file": "sprites/crops/herbs/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "herbs_stage_1",
    "file": "sprites/crops/herbs/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "herbs_stage_2",
    "file": "sprites/crops/herbs/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "inventory_bag",
    "file": "ui/icons/inventory_bag.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "inventory_drop",
    "file": "ui/icons/inventory_drop.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "inventory_sort",
    "file": "ui/icons/inventory_sort.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "inventory_stack",
    "file": "ui/icons/inventory_stack.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "inventory_use",
    "file": "ui/icons/inventory_use.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "kgotla",
    "file": "tiles/sky/kgotla.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "leaf_autumn",
    "file": "particles/leaf_autumn.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "leaf_green",
    "file": "particles/leaf_green.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "lightning",
    "file": "weather/lightning.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "weather"
  },
  {
    "id": "maize_product",
    "file": "sprites/crops/maize/product_maize.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "maize_seed",
    "file": "sprites/crops/maize/seed_maize.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "maize_stage_0",
    "file": "sprites/crops/maize/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "maize_stage_1",
    "file": "sprites/crops/maize/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "maize_stage_2",
    "file": "sprites/crops/maize/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "maize_stage_3",
    "file": "sprites/crops/maize/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "maize_stage_4",
    "file": "sprites/crops/maize/stage_4.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "mama_naledi",
    "file": "sprites/npcs/mama_naledi.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "npcs"
  },
  {
    "id": "market",
    "file": "tiles/sky/market.png",
    "width": 400,
    "height": 300,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "market_buy",
    "file": "ui/icons/market_buy.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "market_cart",
    "file": "sprites/scene-props/market_cart.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "market_contract",
    "file": "ui/icons/market_contract.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "market_portrait",
    "file": "tiles/sky/market_portrait.png",
    "width": 400,
    "height": 400,
    "kind": "pixflux",
    "group": "backgrounds"
  },
  {
    "id": "market_price",
    "file": "ui/icons/market_price.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "market_sell",
    "file": "ui/icons/market_sell.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "market_trade",
    "file": "ui/icons/market_trade.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "market_vendor",
    "file": "sprites/npcs/market_vendor.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "npcs"
  },
  {
    "id": "marula_tree",
    "file": "tiles/decorations/marula_tree.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "material_herb_wild",
    "file": "ui/items/material_herb_wild.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "material_marula",
    "file": "ui/items/material_marula.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "material_reeds",
    "file": "ui/items/material_reeds.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "material_salt",
    "file": "ui/items/material_salt.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "material_stone",
    "file": "ui/items/material_stone.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "material_wood",
    "file": "ui/items/material_wood.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "mill_lvl1",
    "file": "sprites/buildings/mill/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "millet_product",
    "file": "sprites/crops/millet/product_millet.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "millet_seed",
    "file": "sprites/crops/millet/seed_millet.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "millet_stage_0",
    "file": "sprites/crops/millet/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "millet_stage_1",
    "file": "sprites/crops/millet/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "millet_stage_2",
    "file": "sprites/crops/millet/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "millet_stage_3",
    "file": "sprites/crops/millet/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "navigation_bushveld",
    "file": "ui/icons/navigation_bushveld.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "navigation_farm",
    "file": "ui/icons/navigation_farm.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "navigation_kgotla",
    "file": "ui/icons/navigation_kgotla.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "navigation_market",
    "file": "ui/icons/navigation_market.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "navigation_settings",
    "file": "ui/icons/navigation_settings.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "paddock_lvl1",
    "file": "sprites/buildings/paddock/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "panel_dialog",
    "file": "ui/panels/panel_dialog.png",
    "width": 384,
    "height": 256,
    "kind": "ui",
    "group": "ui-assets"
  },
  {
    "id": "panel_sheet",
    "file": "ui/panels/panel_sheet.png",
    "width": 384,
    "height": 512,
    "kind": "ui",
    "group": "ui-assets"
  },
  {
    "id": "panel_titlebar",
    "file": "ui/panels/panel_titlebar.png",
    "width": 256,
    "height": 64,
    "kind": "pixen",
    "group": "ui-assets"
  },
  {
    "id": "pepper_product",
    "file": "sprites/crops/pepper/product_pepper.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "pepper_seed",
    "file": "sprites/crops/pepper/seed_pepper.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "pepper_stage_0",
    "file": "sprites/crops/pepper/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "pepper_stage_1",
    "file": "sprites/crops/pepper/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "pepper_stage_2",
    "file": "sprites/crops/pepper/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "pepper_stage_3",
    "file": "sprites/crops/pepper/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "petal_pink",
    "file": "particles/petal_pink.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "pig_happy",
    "file": "sprites/animals/pig/happy.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "pig_idle",
    "file": "sprites/animals/pig/idle.png",
    "width": 64,
    "height": 48,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "pig_pen_lvl1",
    "file": "sprites/buildings/pig_pen/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "pig_product",
    "file": "sprites/animals/pig/product.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "animals"
  },
  {
    "id": "plot_empty",
    "file": "tiles/ground/plot_empty.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "ground"
  },
  {
    "id": "plot_soil",
    "file": "tiles/ground/plot_soil.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "ground"
  },
  {
    "id": "price_board",
    "file": "sprites/scene-props/price_board.png",
    "width": 48,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "product_cowpeas",
    "file": "ui/items/product_cowpeas.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_egg",
    "file": "ui/items/product_egg.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_groundnuts",
    "file": "ui/items/product_groundnuts.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_herbs",
    "file": "ui/items/product_herbs.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_maize",
    "file": "ui/items/product_maize.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_milk",
    "file": "ui/items/product_milk.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_millet",
    "file": "ui/items/product_millet.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_pepper",
    "file": "ui/items/product_pepper.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_saffron",
    "file": "ui/items/product_saffron.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_sesame",
    "file": "ui/items/product_sesame.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_sorghum",
    "file": "ui/items/product_sorghum.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_tomatoes",
    "file": "ui/items/product_tomatoes.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_watermelon",
    "file": "ui/items/product_watermelon.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "product_wool",
    "file": "ui/items/product_wool.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "quest_board",
    "file": "sprites/scene-props/quest_board.png",
    "width": 48,
    "height": 64,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "rain_cloud",
    "file": "weather/rain_cloud.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "weather"
  },
  {
    "id": "reeds",
    "file": "tiles/decorations/reeds.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "refilwe",
    "file": "sprites/npcs/refilwe.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "npcs"
  },
  {
    "id": "resource_node",
    "file": "sprites/scene-props/resource_node.png",
    "width": 48,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "river_rock",
    "file": "sprites/scene-props/river_rock.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "rock",
    "file": "tiles/decorations/rock.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "saffron_product",
    "file": "sprites/crops/saffron/product_saffron.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "saffron_seed",
    "file": "sprites/crops/saffron/seed_saffron.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "saffron_stage_0",
    "file": "sprites/crops/saffron/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "saffron_stage_1",
    "file": "sprites/crops/saffron/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "saffron_stage_2",
    "file": "sprites/crops/saffron/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "saffron_stage_3",
    "file": "sprites/crops/saffron/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "saffron_stage_4",
    "file": "sprites/crops/saffron/stage_4.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sandstone_rock",
    "file": "tiles/decorations/sandstone_rock.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "decor"
  },
  {
    "id": "seed_cowpeas",
    "file": "ui/items/seed_cowpeas.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_groundnuts",
    "file": "ui/items/seed_groundnuts.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_herbs",
    "file": "ui/items/seed_herbs.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_maize",
    "file": "ui/items/seed_maize.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_millet",
    "file": "ui/items/seed_millet.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_pepper",
    "file": "ui/items/seed_pepper.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_saffron",
    "file": "ui/items/seed_saffron.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_sesame",
    "file": "ui/items/seed_sesame.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_sorghum",
    "file": "ui/items/seed_sorghum.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_tomatoes",
    "file": "ui/items/seed_tomatoes.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "seed_watermelon",
    "file": "ui/items/seed_watermelon.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "sesame_product",
    "file": "sprites/crops/sesame/product_sesame.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sesame_seed",
    "file": "sprites/crops/sesame/seed_sesame.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sesame_stage_0",
    "file": "sprites/crops/sesame/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sesame_stage_1",
    "file": "sprites/crops/sesame/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sesame_stage_2",
    "file": "sprites/crops/sesame/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sesame_stage_3",
    "file": "sprites/crops/sesame/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "smoke_puff",
    "file": "particles/smoke_puff.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "snowflake",
    "file": "particles/snowflake.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "social_gift",
    "file": "ui/icons/social_gift.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "social_npc",
    "file": "ui/icons/social_npc.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "social_quest",
    "file": "ui/icons/social_quest.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "social_reputation",
    "file": "ui/icons/social_reputation.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "sorghum_product",
    "file": "sprites/crops/sorghum/product_sorghum.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sorghum_seed",
    "file": "sprites/crops/sorghum/seed_sorghum.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sorghum_stage_0",
    "file": "sprites/crops/sorghum/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sorghum_stage_1",
    "file": "sprites/crops/sorghum/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sorghum_stage_2",
    "file": "sprites/crops/sorghum/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sorghum_stage_3",
    "file": "sprites/crops/sorghum/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "sparkle_gold",
    "file": "particles/sparkle_gold.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "sparkle_white",
    "file": "particles/sparkle_white.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "stall_canopy",
    "file": "sprites/scene-props/stall_canopy.png",
    "width": 96,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "status_healthy",
    "file": "ui/icons/status_healthy.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "status_hungry",
    "file": "ui/icons/status_hungry.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "status_ready",
    "file": "ui/icons/status_ready.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "status_sick",
    "file": "ui/icons/status_sick.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "status_thirsty",
    "file": "ui/icons/status_thirsty.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "status_withered",
    "file": "ui/icons/status_withered.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "stone_bench",
    "file": "sprites/scene-props/stone_bench.png",
    "width": 48,
    "height": 32,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "sun_glow",
    "file": "weather/sun_glow.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "weather"
  },
  {
    "id": "tomatoes_product",
    "file": "sprites/crops/tomatoes/product_tomatoes.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tomatoes_seed",
    "file": "sprites/crops/tomatoes/seed_tomatoes.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tomatoes_stage_0",
    "file": "sprites/crops/tomatoes/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tomatoes_stage_1",
    "file": "sprites/crops/tomatoes/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tomatoes_stage_2",
    "file": "sprites/crops/tomatoes/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tomatoes_stage_3",
    "file": "sprites/crops/tomatoes/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tomatoes_stage_4",
    "file": "sprites/crops/tomatoes/stage_4.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "tool_basket",
    "file": "ui/items/tool_basket.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "tool_canteen",
    "file": "ui/items/tool_canteen.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "tool_field_scope",
    "file": "ui/items/tool_field_scope.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "tool_hoe",
    "file": "ui/items/tool_hoe.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "tool_pickaxe",
    "file": "ui/items/tool_pickaxe.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "tool_sickle",
    "file": "ui/items/tool_sickle.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "tool_watering_can",
    "file": "ui/items/tool_watering_can.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "item-icons"
  },
  {
    "id": "water_drop",
    "file": "particles/water_drop.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "fx"
  },
  {
    "id": "watermelon_product",
    "file": "sprites/crops/watermelon/product_watermelon.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_seed",
    "file": "sprites/crops/watermelon/seed_watermelon.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_stage_0",
    "file": "sprites/crops/watermelon/stage_0.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_stage_1",
    "file": "sprites/crops/watermelon/stage_1.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_stage_2",
    "file": "sprites/crops/watermelon/stage_2.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_stage_3",
    "file": "sprites/crops/watermelon/stage_3.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_stage_4",
    "file": "sprites/crops/watermelon/stage_4.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "watermelon_stage_5",
    "file": "sprites/crops/watermelon/stage_5.png",
    "width": 32,
    "height": 64,
    "kind": "pixen",
    "group": "crops"
  },
  {
    "id": "weather_cloud",
    "file": "ui/icons/weather_cloud.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "weather_drought",
    "file": "ui/icons/weather_drought.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "weather_rain",
    "file": "ui/icons/weather_rain.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "weather_storm",
    "file": "ui/icons/weather_storm.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "weather_sun",
    "file": "ui/icons/weather_sun.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "weather_wind",
    "file": "ui/icons/weather_wind.png",
    "width": 32,
    "height": 32,
    "kind": "pixen",
    "group": "icons"
  },
  {
    "id": "well_lvl1",
    "file": "sprites/buildings/well/lvl1.png",
    "width": 96,
    "height": 64,
    "kind": "pixen",
    "group": "buildings"
  },
  {
    "id": "wild_berry",
    "file": "sprites/scene-props/wild_berry.png",
    "width": 48,
    "height": 48,
    "kind": "pixen",
    "group": "scene-props"
  },
  {
    "id": "wind_swirl",
    "file": "weather/wind_swirl.png",
    "width": 64,
    "height": 64,
    "kind": "pixen",
    "group": "weather"
  }
];

export const ASSETS: Record<string, GeneratedAsset> = Object.fromEntries(
  ASSET_MANIFEST.map((a) => [a.id, a]),
);

export const ASSET_GROUPS: Record<string, string[]> = {
  "decor": [
    "acacia_tree",
    "baobab_tree",
    "bush",
    "fence",
    "flower_patch",
    "grass_tuft",
    "marula_tree",
    "reeds",
    "rock",
    "sandstone_rock"
  ],
  "scene-props": [
    "animal_track",
    "bush_camp",
    "cave_entrance",
    "community_circle",
    "elder_chair",
    "fire_pit",
    "food_stall",
    "goods_display",
    "herb_garden",
    "market_cart",
    "price_board",
    "quest_board",
    "resource_node",
    "river_rock",
    "stall_canopy",
    "stone_bench",
    "wild_berry"
  ],
  "icons": [
    "animals_collect",
    "animals_feed",
    "animals_heal",
    "animals_pet",
    "animals_shelter",
    "buildings_construct",
    "buildings_demolish",
    "buildings_repair",
    "buildings_upgrade",
    "currency_gem",
    "currency_pula",
    "currency_token",
    "farming_fertilize",
    "farming_harvest",
    "farming_plant",
    "farming_soil",
    "farming_water",
    "farming_weed",
    "inventory_bag",
    "inventory_drop",
    "inventory_sort",
    "inventory_stack",
    "inventory_use",
    "market_buy",
    "market_contract",
    "market_price",
    "market_sell",
    "market_trade",
    "navigation_bushveld",
    "navigation_farm",
    "navigation_kgotla",
    "navigation_market",
    "navigation_settings",
    "social_gift",
    "social_npc",
    "social_quest",
    "social_reputation",
    "status_healthy",
    "status_hungry",
    "status_ready",
    "status_sick",
    "status_thirsty",
    "status_withered",
    "weather_cloud",
    "weather_drought",
    "weather_rain",
    "weather_storm",
    "weather_sun",
    "weather_wind"
  ],
  "buildings": [
    "barn_lvl1",
    "coop_lvl1",
    "goat_pen_lvl1",
    "mill_lvl1",
    "paddock_lvl1",
    "pig_pen_lvl1",
    "well_lvl1"
  ],
  "item-icons": [
    "building_barn",
    "building_borehole",
    "building_coop",
    "building_goat_pen",
    "building_greenhouse",
    "building_mill",
    "building_paddock",
    "building_pig_pen",
    "building_well",
    "material_herb_wild",
    "material_marula",
    "material_reeds",
    "material_salt",
    "material_stone",
    "material_wood",
    "product_cowpeas",
    "product_egg",
    "product_groundnuts",
    "product_herbs",
    "product_maize",
    "product_milk",
    "product_millet",
    "product_pepper",
    "product_saffron",
    "product_sesame",
    "product_sorghum",
    "product_tomatoes",
    "product_watermelon",
    "product_wool",
    "seed_cowpeas",
    "seed_groundnuts",
    "seed_herbs",
    "seed_maize",
    "seed_millet",
    "seed_pepper",
    "seed_saffron",
    "seed_sesame",
    "seed_sorghum",
    "seed_tomatoes",
    "seed_watermelon",
    "tool_basket",
    "tool_canteen",
    "tool_field_scope",
    "tool_hoe",
    "tool_pickaxe",
    "tool_sickle",
    "tool_watering_can"
  ],
  "backgrounds": [
    "bushveld_riverbank",
    "bushveld_savanna",
    "farm_day",
    "farm_night",
    "farm_sunset",
    "kgotla",
    "market",
    "market_portrait"
  ],
  "npcs": [
    "bushveld_scout",
    "elder_neo",
    "mama_naledi",
    "market_vendor",
    "refilwe"
  ],
  "ui-assets": [
    "button_danger",
    "button_primary",
    "button_secondary",
    "panel_dialog",
    "panel_sheet",
    "panel_titlebar"
  ],
  "animals": [
    "chicken_happy",
    "chicken_idle",
    "chicken_product",
    "cow_happy",
    "cow_idle",
    "cow_product",
    "goat_happy",
    "goat_idle",
    "goat_product",
    "pig_happy",
    "pig_idle",
    "pig_product"
  ],
  "weather": [
    "cloud_storm",
    "cloud_white",
    "lightning",
    "rain_cloud",
    "sun_glow",
    "wind_swirl"
  ],
  "fx": [
    "coin",
    "dirt_chunk",
    "dust_puff",
    "heart",
    "leaf_autumn",
    "leaf_green",
    "petal_pink",
    "smoke_puff",
    "snowflake",
    "sparkle_gold",
    "sparkle_white",
    "water_drop"
  ],
  "crops": [
    "cowpeas_product",
    "cowpeas_seed",
    "cowpeas_stage_0",
    "cowpeas_stage_1",
    "cowpeas_stage_2",
    "cowpeas_stage_3",
    "groundnuts_product",
    "groundnuts_seed",
    "groundnuts_stage_0",
    "groundnuts_stage_1",
    "groundnuts_stage_2",
    "groundnuts_stage_3",
    "groundnuts_stage_4",
    "herbs_product",
    "herbs_seed",
    "herbs_stage_0",
    "herbs_stage_1",
    "herbs_stage_2",
    "maize_product",
    "maize_seed",
    "maize_stage_0",
    "maize_stage_1",
    "maize_stage_2",
    "maize_stage_3",
    "maize_stage_4",
    "millet_product",
    "millet_seed",
    "millet_stage_0",
    "millet_stage_1",
    "millet_stage_2",
    "millet_stage_3",
    "pepper_product",
    "pepper_seed",
    "pepper_stage_0",
    "pepper_stage_1",
    "pepper_stage_2",
    "pepper_stage_3",
    "saffron_product",
    "saffron_seed",
    "saffron_stage_0",
    "saffron_stage_1",
    "saffron_stage_2",
    "saffron_stage_3",
    "saffron_stage_4",
    "sesame_product",
    "sesame_seed",
    "sesame_stage_0",
    "sesame_stage_1",
    "sesame_stage_2",
    "sesame_stage_3",
    "sorghum_product",
    "sorghum_seed",
    "sorghum_stage_0",
    "sorghum_stage_1",
    "sorghum_stage_2",
    "sorghum_stage_3",
    "tomatoes_product",
    "tomatoes_seed",
    "tomatoes_stage_0",
    "tomatoes_stage_1",
    "tomatoes_stage_2",
    "tomatoes_stage_3",
    "tomatoes_stage_4",
    "watermelon_product",
    "watermelon_seed",
    "watermelon_stage_0",
    "watermelon_stage_1",
    "watermelon_stage_2",
    "watermelon_stage_3",
    "watermelon_stage_4",
    "watermelon_stage_5"
  ],
  "ground": [
    "grass_base",
    "grass_dirt",
    "grass_dry",
    "grass_path",
    "grass_water",
    "plot_empty",
    "plot_soil"
  ]
};

/** Absolute URL (served by the web app from apps/web/public). */
export function assetUrl(id: string): string {
  const a = ASSETS[id];
  return a ? `/assets/${a.file}` : '';
}

/** True when the id exists in the generated manifest. */
export function hasAsset(id: string): boolean {
  return id in ASSETS;
}
