-- ============================================
-- MOLEMISI SEED DATA
-- Development seed data for testing
-- ============================================

-- Note: This seed data assumes a test user has been created via Supabase Auth
-- The user ID should be replaced with an actual auth user ID

-- Example seed data (run after creating a test user):
-- Replace 'YOUR_AUTH_USER_ID' with the actual UUID from auth.users

-- ============================================
-- TEST PROFILE
-- ============================================
-- INSERT INTO public.profiles (id, display_name, farm_name, currency)
-- VALUES ('YOUR_AUTH_USER_ID', 'Test Farmer', 'Sunny Acres', 1000);

-- ============================================
-- TEST FARM
-- ============================================
-- INSERT INTO public.farms (id, user_id, name, plot_count)
-- VALUES ('YOUR_FARM_ID', 'YOUR_AUTH_USER_ID', 'Sunny Acres', 6);

-- ============================================
-- TEST PLOTS
-- ============================================
-- INSERT INTO public.farm_plots (farm_id, slot_index, state)
-- VALUES
--   ('YOUR_FARM_ID', 0, 'EMPTY'),
--   ('YOUR_FARM_ID', 1, 'EMPTY'),
--   ('YOUR_FARM_ID', 2, 'EMPTY'),
--   ('YOUR_FARM_ID', 3, 'EMPTY'),
--   ('YOUR_FARM_ID', 4, 'EMPTY'),
--   ('YOUR_FARM_ID', 5, 'EMPTY');

-- ============================================
-- TEST INVENTORY
-- ============================================
-- INSERT INTO public.inventory (farm_id, item_type, item_category, quantity, quality)
-- VALUES
--   ('YOUR_FARM_ID', 'sorghum_seed', 'seed', 10, 'normal'),
--   ('YOUR_FARM_ID', 'maize_seed', 'seed', 5, 'normal');

-- ============================================
-- MARKET PRICES (server-only table)
-- Canonical rows GENERATED by scripts/generate-market-seed.cjs from the
-- authoritative @molemisi/game-config catalogue. base_price = ItemDef.baseValue
-- (the price of record). Seeds are buyable but the Co-op sell path rejects them
-- (MarketService.sellItem guard); tools are excluded. ON CONFLICT DO NOTHING keeps
-- this idempotent after migration 20260924000000 has reconciled the table.
-- ============================================
INSERT INTO public.market_prices (item_type, item_name, base_price, current_price, category)
VALUES
  ('sorghum_seed', 'Mabele Seed', 2, 2, 'seed'),
  ('millet_seed', 'Lebelebele Seed', 2, 2, 'seed'),
  ('maize_seed', 'Mmidi Seed', 3, 3, 'seed'),
  ('cowpeas_seed', 'Dinawa Seed', 3, 3, 'seed'),
  ('tomatoes_seed', 'Tamati Seed', 5, 5, 'seed'),
  ('watermelon_seed', 'Legapu Seed', 6, 6, 'seed'),
  ('groundnuts_seed', 'Manoko Seed', 8, 8, 'seed'),
  ('sesame_seed', 'Sesame Seed', 10, 10, 'seed'),
  ('pepper_seed', 'Pepere Seed', 12, 12, 'seed'),
  ('herbs_seed', 'Herbs Seed', 16, 16, 'seed'),
  ('morula_seed', 'Morula Seed', 28, 28, 'seed'),
  ('sorghum', 'Sorghum', 3, 3, 'crop'),
  ('millet', 'Millet', 4, 4, 'crop'),
  ('maize', 'Maize', 5, 5, 'crop'),
  ('cowpeas', 'Cowpeas', 6, 6, 'crop'),
  ('tomatoes', 'Tomatoes', 10, 10, 'crop'),
  ('watermelon', 'Watermelon', 11, 11, 'crop'),
  ('groundnuts', 'Groundnuts', 11, 11, 'crop'),
  ('sesame', 'Sesame', 15, 15, 'crop'),
  ('pepper', 'Pepper', 17, 17, 'crop'),
  ('herbs', 'Herbs', 25, 25, 'crop'),
  ('morula', 'Morula', 46, 46, 'crop'),
  ('eggs', 'Eggs', 5, 5, 'product'),
  ('milk', 'Milk', 15, 15, 'product'),
  ('truffle', 'Truffle', 50, 50, 'product'),
  ('manure', 'Manure', 1, 1, 'product'),
  ('wood', 'Wood', 2, 2, 'material'),
  ('hardwood', 'Hardwood', 8, 8, 'material'),
  ('stone', 'Stone', 3, 3, 'material'),
  ('clay', 'Clay', 3, 3, 'material'),
  ('palm_fiber', 'Palm Fiber', 4, 4, 'material'),
  ('thatch', 'Thatch / Reeds', 3, 3, 'material'),
  ('phane', 'Mophane Worms', 10, 10, 'material'),
  ('poleto', 'Plank', 7, 7, 'crafted'),
  ('thapo', 'Rope', 18, 18, 'crafted'),
  ('setena', 'Brick', 11, 11, 'crafted'),
  ('bupi', 'Flour', 20, 20, 'crafted'),
  ('borotho', 'Bread', 60, 60, 'crafted')
ON CONFLICT (item_type) DO NOTHING;
