#!/usr/bin/env node
/**
 * Molemisi Pixel — font pipeline.
 *
 * Canonical font: assets/branding/font/MolemisiPixel-Bold.ttf
 *   Generated by PixelLab /generate-font-pro (scripts/generate-font.mjs) using the
 *   16-bit RPG style description. This script syncs it into the web app.
 *
 * Fallback font: assets/branding/font/MolemisiPixel-Bold-handcrafted.ttf
 *   Compiled from the hand-drawn glyph bitmaps (scripts/lib/glyphs.mjs) via the
 *   zero-dependency TTF compiler (scripts/lib/ttf.mjs). Kept as an offline,
 *   deterministic regeneration path if the AI font needs replacing.
 *
 * Usage:
 *   node scripts/build-font.mjs              # sync canonical font to web app
 *   node scripts/build-font.mjs --rebuild    # recompile the hand-crafted fallback
 *   node scripts/build-font.mjs --specimen   # print ASCII specimen of hand-drawn glyphs
 */
import { writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'assets', 'branding', 'font');
const args = process.argv.slice(2);

mkdirSync(outDir, { recursive: true });

/* ---------------------------------------------------------------- helpers */

function syncToWebApp() {
  const src = join(outDir, 'MolemisiPixel-Bold.ttf');
  if (!existsSync(src)) {
    console.error('[font] Canonical MolemisiPixel-Bold.ttf missing — run scripts/generate-font.mjs');
    process.exit(1);
  }
  const webFontDir = join(root, 'apps', 'web', 'public', 'fonts');
  mkdirSync(webFontDir, { recursive: true });
  copyFileSync(src, join(webFontDir, 'MolemisiPixel-Bold.ttf'));
  console.log('[font] Synced canonical font to apps/web/public/fonts/');
}

function rebuildHandcrafted() {
  // Dynamic imports so the common path doesn't load the compiler at all
  return Promise.all([import('./lib/ttf.mjs'), import('./lib/glyphs.mjs')]).then(
    ([{ buildTTF }, { GLYPHS }]) => {
      // Validate glyphs: uniform row width
      let bad = 0;
      for (const [ch, rows] of Object.entries(GLYPHS)) {
        if (rows.length !== 12) {
          console.error(`[font] '${ch}' has ${rows.length} rows (expect 12)`);
          bad++;
        }
        const w = rows[0].length;
        if (rows.some((r) => r.length !== w)) {
          console.error(`[font] '${ch}' has ragged rows`);
          bad++;
        }
      }
      if (bad) process.exit(1);

      const ttf = buildTTF(GLYPHS, {
        familyName: 'Molemisi Pixel',
        styleName: 'Bold',
        ascender: 10 * 128,
        descender: 2 * 128,
      });
      const out = join(outDir, 'MolemisiPixel-Bold-handcrafted.ttf');
      writeFileSync(out, ttf);
      console.log(
        `[font] Wrote MolemisiPixel-Bold-handcrafted.ttf (${(ttf.length / 1024).toFixed(1)} KB, ${Object.keys(GLYPHS).length} glyphs)`
      );
      return GLYPHS;
    }
  );
}

function printSpecimen(GLYPHS) {
  console.log('\nMolemisi Pixel (hand-crafted fallback) — specimen\n');
  const chars = Object.keys(GLYPHS);
  for (let i = 0; i < chars.length; i += 8) {
    const slice = chars.slice(i, i + 8);
    for (let row = 0; row < 12; row++) {
      console.log(slice.map((ch) => GLYPHS[ch][row]).join('  '));
    }
    console.log('');
  }
}

/* ------------------------------------------------------------------ main */

const wantsRebuild = args.includes('--rebuild');
const wantsSpecimen = args.includes('--specimen');

if (wantsRebuild || wantsSpecimen) {
  const glyphs = await rebuildHandcrafted();
  if (wantsSpecimen) printSpecimen(glyphs);
}

syncToWebApp();
