#!/usr/bin/env node
/**
 * Molemisi — Asset sync + manifest generation.
 *
 * 1. Copies the generated assets/ directory into apps/web/public/assets/
 *    so the Next.js web app (which hosts the Phaser client) can serve them
 *    over HTTP at /assets/...
 * 2. Emits apps/game/src/generated-assets.ts — a typed manifest derived from
 *    assets/manifest.json — so PreloadScene can register every asset with
 *    Phaser's loader without a runtime fetch.
 *
 * Run from the repo root:  node scripts/sync-assets.mjs
 * (also wired into `pnpm dev` / `pnpm build` via predev/prebuild.)
 */
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const assetsDir = join(root, 'assets');
// Where the assets are served from over HTTP:
//  - web app (Next.js public folder) hosts the game in the browser
//  - game app (Vite public folder) serves the standalone build on :3002
const publicDirs = [
  join(root, 'apps', 'web', 'public', 'assets'),
  join(root, 'apps', 'game', 'public', 'assets'),
];
const manifestPath = join(assetsDir, 'manifest.json');
const outTsPath = join(root, 'apps', 'game', 'src', 'generated-assets.ts');

if (!existsSync(manifestPath)) {
  console.warn(`[sync-assets] No ${manifestPath} found — skipping. Run the asset generator first.`);
  process.exit(0);
}

// 1. Copy the whole assets tree into each public folder.
let copied = 0;
for (const publicDir of publicDirs) {
  mkdirSync(publicDir, { recursive: true });
  cpSync(assetsDir, publicDir, { recursive: true, force: true });
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(join(dir, entry.name));
      else copied++;
    }
  };
  walk(publicDir);
}

// 2. Read the manifest and emit the typed module.
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const entries = Object.entries(manifest)
  .map(([id, e]) => ({
    id,
    file: e.file,
    width: e.size?.w ?? 0,
    height: e.size?.h ?? 0,
    kind: e.kind ?? 'image',
    group: e.group ?? 'misc',
  }))
  .sort((a, b) => a.id.localeCompare(b.id));

const groups = {};
for (const e of entries) (groups[e.group] ??= []).push(e.id);

const ts = `// AUTO-GENERATED by scripts/sync-assets.mjs — do not edit.
// Derived from assets/manifest.json (written by scripts/generate-pixellab-assets.mjs).

export interface GeneratedAsset {
  id: string;
  file: string;
  width: number;
  height: number;
  kind: string;
  group: string;
}

export const ASSET_MANIFEST: GeneratedAsset[] = ${JSON.stringify(entries, null, 2)};

export const ASSETS: Record<string, GeneratedAsset> = Object.fromEntries(
  ASSET_MANIFEST.map((a) => [a.id, a]),
);

export const ASSET_GROUPS: Record<string, string[]> = ${JSON.stringify(groups, null, 2)};

/** Absolute URL (served by the web app from apps/web/public). */
export function assetUrl(id: string): string {
  const a = ASSETS[id];
  return a ? \`/assets/\${a.file}\` : '';
}

/** True when the id exists in the generated manifest. */
export function hasAsset(id: string): boolean {
  return id in ASSETS;
}
`;

writeFileSync(outTsPath, ts, 'utf8');

for (const publicDir of publicDirs) {
  console.log(`[sync-assets] Copied assets -> ${publicDir.replace(root, '.')}`);
}
console.log(`[sync-assets] ${copied} files synced total`);
console.log(
  `[sync-assets] Wrote ${outTsPath.replace(root, '.')} (${entries.length} assets, ${Object.keys(groups).length} groups)`,
);
