-- Reconcile market_prices with the authoritative @molemisi/game-config catalogue.
--
-- Background (docs/26_Inventory_Crafting_System.md §11.1): the Co-op market is the
-- read/write surface for the inventory system. Every non-tool item must have exactly
-- one market_prices row whose base_price equals the item's ItemDef.baseValue, and no
-- row may reference a slug that no longer exists in the catalogue.
--
-- The two historical seeders (migration 20260902000003_market_dynamic_pricing.sql and
-- supabase/seed/seed.sql) were written for a PRE-REFACTOR economy and had drifted hard:
--   * Orphan rows for items that do not exist (saffron, saffron_seed, wool, honey,
--     herb_bundle, wild_saffron, egg, goat_milk, cow_milk, flour, butter, cheese,
--     leather, bread).
--   * Missing rows for real sellable items (morula, eggs, milk, manure, hardwood,
--     clay, palm_fiber, thatch, phane, poleto, thapo, setena, bupi, borotho) — so
--     getDynamicPrice() returned 0 and the Co-op refused to quote/sell them.
--   * Wrong base_price on every crop/seed/milk/wood/stone row (4-8x the catalogue).
--
-- This migration is generated by scripts/generate-market-seed.cjs so the row list stays
-- in lock-step with the catalogue; re-run the script and this migration together if the
-- catalogue changes. It is idempotent: safe to re-apply.
--
-- NOTE: `current_price` is reset to base_price because the live values in the table are
-- the stale pre-refactor numbers and carry no legitimate market signal. Live drift
-- resumes from the service's 6-hour cycle after this runs.

-- 1) Remove orphan rows: any slug currently in market_prices that is not in the catalogue.
DELETE FROM public.market_prices
WHERE item_type NOT IN (
  'sorghum_seed', 'millet_seed', 'maize_seed', 'cowpeas_seed', 'tomatoes_seed',
  'watermelon_seed', 'groundnuts_seed', 'sesame_seed', 'pepper_seed', 'herbs_seed',
  'morula_seed', 'sorghum', 'millet', 'maize', 'cowpeas', 'tomatoes', 'watermelon',
  'groundnuts', 'sesame', 'pepper', 'herbs', 'morula', 'eggs', 'milk', 'truffle',
  'manure', 'wood', 'hardwood', 'stone', 'clay', 'palm_fiber', 'thatch', 'phane',
  'poleto', 'thapo', 'setena', 'bupi', 'borotho'
);

-- 2) Upsert every canonical row. Corrects stale prices and adds the missing ones.
INSERT INTO public.market_prices (item_type, item_name, base_price, current_price, category)
VALUES
  ('sorghum_seed', 'Mabele Seed', 2, 2, 'seed'),
  ('millet_seed', 'Lebelebele Seed', 2, 2, 'seed'),
  ('maize_seed', 'Mmidi Seed', 3, 3, 'seed'),
  ('cowpeas_seed', 'Dinawa Seed', 3, 3, 'seed'),
  ('tomatoes_seed', 'Tamati Seed', 5, 5, 'seed'),
  ('watermelon_seed', 'Legapu Seed', 6, 6, 'seed'),
  ('groundnuts_seed', 'Manoko Seed', 8, 8, 'seed'),
  ('sesame_seed', 'Sesame Seed', 10, 10, 'seed'),
  ('pepper_seed', 'Pepere Seed', 12, 12, 'seed'),
  ('herbs_seed', 'Herbs Seed', 16, 16, 'seed'),
  ('morula_seed', 'Morula Seed', 28, 28, 'seed'),
  ('sorghum', 'Sorghum', 3, 3, 'crop'),
  ('millet', 'Millet', 4, 4, 'crop'),
  ('maize', 'Maize', 5, 5, 'crop'),
  ('cowpeas', 'Cowpeas', 6, 6, 'crop'),
  ('tomatoes', 'Tomatoes', 10, 10, 'crop'),
  ('watermelon', 'Watermelon', 11, 11, 'crop'),
  ('groundnuts', 'Groundnuts', 11, 11, 'crop'),
  ('sesame', 'Sesame', 15, 15, 'crop'),
  ('pepper', 'Pepper', 17, 17, 'crop'),
  ('herbs', 'Herbs', 25, 25, 'crop'),
  ('morula', 'Morula', 46, 46, 'crop'),
  ('eggs', 'Eggs', 5, 5, 'product'),
  ('milk', 'Milk', 15, 15, 'product'),
  ('truffle', 'Truffle', 50, 50, 'product'),
  ('manure', 'Manure', 1, 1, 'product'),
  ('wood', 'Wood', 2, 2, 'material'),
  ('hardwood', 'Hardwood', 8, 8, 'material'),
  ('stone', 'Stone', 3, 3, 'material'),
  ('clay', 'Clay', 3, 3, 'material'),
  ('palm_fiber', 'Palm Fiber', 4, 4, 'material'),
  ('thatch', 'Thatch / Reeds', 3, 3, 'material'),
  ('phane', 'Mophane Worms', 10, 10, 'material'),
  ('poleto', 'Plank', 7, 7, 'crafted'),
  ('thapo', 'Rope', 18, 18, 'crafted'),
  ('setena', 'Brick', 11, 11, 'crafted'),
  ('bupi', 'Flour', 20, 20, 'crafted'),
  ('borotho', 'Bread', 60, 60, 'crafted')
ON CONFLICT (item_type) DO UPDATE SET
  base_price = EXCLUDED.base_price,
  current_price = EXCLUDED.base_price,
  item_name = EXCLUDED.item_name,
  category = EXCLUDED.category,
  updated_at = NOW();
