/**
 * Pixel-art item icons generated by PixelLab (assets/ui/items/).
 *
 * Maps itemType / cropType → /assets/ui/items/<name>.png with emoji fallback.
 * Used by Inventory, Market and any screen that displays game items.
 */

const PIXEL_ITEM_ICONS: Record<string, string> = {
  // Seeds
  sorghum_seed: 'seed_sorghum',
  maize_seed: 'seed_maize',
  millet_seed: 'seed_millet',
  cowpeas_seed: 'seed_cowpeas',
  groundnuts_seed: 'seed_groundnuts',
  sesame_seed: 'seed_sesame',
  watermelon_seed: 'seed_watermelon',
  tomatoes_seed: 'seed_tomatoes',
  pepper_seed: 'seed_pepper',
  herbs_seed: 'seed_herbs',
  saffron_seed: 'seed_saffron',

  // Crop products
  sorghum: 'product_sorghum',
  maize: 'product_maize',
  millet: 'product_millet',
  cowpeas: 'product_cowpeas',
  groundnuts: 'product_groundnuts',
  sesame: 'product_sesame',
  watermelon: 'product_watermelon',
  tomatoes: 'product_tomatoes',
  pepper: 'product_pepper',
  herbs: 'product_herbs',
  saffron: 'product_saffron',

  // Animal products
  egg: 'product_egg',
  // items.ts slug is `eggs` (plural) — the singular `egg` key above never matched.
  eggs: 'product_egg',
  milk: 'product_milk',
  wool: 'product_wool',

  // Materials
  wood: 'material_wood',
  acacia_wood: 'material_wood',
  stone: 'material_stone',
  granite_stone: 'material_stone',
  reeds: 'material_reeds',
  river_reeds: 'material_reeds',
  marula: 'material_marula',
  marula_fruit: 'material_marula',
  salt: 'material_salt',
  mineral_salt: 'material_salt',
  herb_wild: 'material_herb_wild',
  wild_herbs: 'material_herb_wild',

  // Bushveld materials (02 §6.2) — files use the Setswana names
  clay: 'material_letsopa',
  letsopa: 'material_letsopa',
  palm_fiber: 'material_mokolwane',
  mokolwane: 'material_mokolwane',
  thatch: 'material_lotlhaka',
  lotlhaka: 'material_lotlhaka',
  phane: 'material_phane',
  manure: 'material_manyoro',
  manyoro: 'material_manyoro',

  // Crafted goods (02 §6.3)
  poleto: 'product_poleto',
  thapo: 'product_thapo',
  setena: 'product_setena',
  bupi: 'product_bupi',
  borotho: 'product_borotho',

  // Morula (F18 — the crop that replaced Saffron)
  morula: 'product_morula',
  morula_seed: 'seed_morula',

  // Tools
  // items.ts slugs: `mogoma` = Hoe, `selepe` = Axe, `pickaxe` = Pickaxe.
  // The map used generic names (`hoe`/`pickaxe`) that never matched those slugs,
  // so the Hoe and Axe fell back to emoji. No axe sprite exists, so the Axe
  // reuses the pickaxe art (same tools/equipment family) — accurate as possible
  // until a dedicated axe asset is generated.
  mogoma: 'tool_hoe',
  hoe: 'tool_hoe',
  watering_can: 'tool_watering_can',
  sickle: 'tool_sickle',
  basket: 'tool_basket',
  woven_basket: 'tool_basket',
  selepe: 'tool_pickaxe',
  pickaxe: 'tool_pickaxe',
  stone_pickaxe: 'tool_pickaxe',
  canteen: 'tool_canteen',
  clay_canteen: 'tool_canteen',
  field_scope: 'tool_field_scope',

  // Buildings (inventory blueprints)
  well: 'building_well',
  coop: 'building_coop',
  chicken_coop: 'building_coop',
  barn: 'building_barn',
  goat_pen: 'building_goat_pen',
  goat_kraal: 'building_goat_pen',
  mill: 'building_mill',
  paddock: 'building_paddock',
  pig_pen: 'building_pig_pen',
  borehole: 'building_borehole',
  borehole_well: 'building_borehole',
  greenhouse: 'building_greenhouse',
};

/** Pixel icon URL for an itemType/cropType, or null when unknown. */
export function pixelItemIcon(itemType?: string | null): string | null {
  if (!itemType) return null;
  const key = PIXEL_ITEM_ICONS[itemType];
  return key ? `/assets/ui/items/${key}.png` : null;
}

/**
 * Resolve the best icon for an inventory item: exact itemType first, then the
 * crop part of a seed type, then null (caller shows the emoji fallback).
 */
export function resolveItemIcon(itemType?: string | null): string | null {
  if (!itemType) return null;
  if (PIXEL_ITEM_ICONS[itemType]) return pixelItemIcon(itemType);
  // Seeds like "tomatoes_seed" → crop icon "product_tomatoes"
  if (itemType.endsWith('_seed')) {
    const crop = itemType.replace(/_seed$/, '');
    if (PIXEL_ITEM_ICONS[crop]) return pixelItemIcon(crop);
  }
  return null;
}

export { PIXEL_ITEM_ICONS };
